{% set name = "cruft" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5350ca3ef7b671409f9b24e8e0bd73d870433aa6b5abbf6e7b9b73f7b4adef0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-cache-dir -vvv
  entry_points:
    - cruft = cruft._cli:app

requirements:
  host:
    - python
    - pip
    - poetry >=0.12
  run:
    - python >=3.6
    - cookiecutter >=1.6,<2.0
    - gitpython >=3.0,<4.0
    - typer >=0.3.1,<0.5.0
    - click >=7.1.2,<9.0.0
    - importlib_metadata >=3.4,<4.0

test:
  requires:
    - git
  imports:
    - cruft
    - cruft._commands
  commands:
    - cruft --help

about:
  home: https://github.com/cruft/cruft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Maintain all the necessary boilerplate for packaging and building projects separate from the code you intentionally write.
  description: |
    Allows you to maintain all the necessary cruft for packaging and
    building projects separate from the code you intentionally write.
    Built on-top of CookieCutter.
  doc_url: https://cruft.github.io/cruft/
  dev_url: https://github.com/cruft/cruft

extra:
  recipe-maintainers:
    - Zeitsperre
    - samj1912
