{% set name = "cruft" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cruft-{{ version }}.tar.gz
  sha256: 57455d33a60684c945d501dcea2b1c57dc0fb200a0090f07c83da1603382cbb1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cruft = cruft._cli:app

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.8
  run:
    - python >=3.7
    - click >=7.1.2
    - cookiecutter >=1.7
    - gitpython >=3.0
    - typer >=0.4.0
    - importlib-metadata >=2.0.0,<5.0.0

test:
  requires:
    - pip
    - git
  imports:
    - cruft
    - cruft._commands
  commands:
    - pip check
    - cruft --help

about:
  home: https://github.com/cruft/cruft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Maintain all the necessary boilerplate for packaging and building projects separate from the code you intentionally write.
  description: |
    Allows you to maintain all the necessary cruft for packaging and
    building projects separate from the code you intentionally write.
    Built on-top of CookieCutter.
  doc_url: https://cruft.github.io/cruft/
  dev_url: https://github.com/cruft/cruft

extra:
  recipe-maintainers:
    - maresb
    - Zeitsperre
    - samj1912
